name: Docs build

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install sphinx and requirements
      run: |
        apt-get update -y 
        # git needed by setuptools-scm in pyproject.toml
        apt-get install -y git
        pip install -e .
        pip install -U -r doc/requirements-docs.txt
    - name: Build Sphinx html
      run: |
        cd doc
        make html
        cd ..
    - name: Upload artifacts
      if: success() && github.event_name == "push"
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: doc/_build/html/
