name: Docs build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "sudo apt-get update -y && sudo apt-get install -y git && sudo pip install -U -r doc/requirements-docs.txt"
        docs-folder: "doc/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: doc/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # If pushing into main branch, also deploy to github pages
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/html